---
title: "Project"
author: "Massiel Payero Garcia"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(corrplot)
library(viridis)
```


```{r}
accident <- US_Accidents_March23_sampled_500k
accident
```


```{r}
# extract time variables
accident <- accident %>%
  mutate(
    Start_Hour = hour(Start_Time),
    Start_Month = month(Start_Time, label = TRUE),
    Start_Day = wday(Start_Time, label = TRUE),
    Start_Year = year(Start_Time)
  )
```


```{r}
# accidents by Start_Time hour
hour_plot <- ggplot(accident, aes(x = Start_Hour)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
  scale_x_continuous(
    breaks = seq(0, 23, by = 2),
    minor_breaks = NULL
  ) +
  labs(title = "Accidents by Hour of Day",
       x = "Hour of Day (0-23)",
       y = "Number of Accidents") +
  theme_minimal() +
  theme(
  )

print(hour_plot)
```

```{r}
# 2 peaks: 7-8 AM and 4-5 PM, rush-hour times
```


```{r}
# accidents by day of week
dow_plot <- ggplot(accident, aes(x = Start_Day)) +
  geom_bar(fill = "steelblue") +
  labs(title = "Accidents by Day of Week",
       x = "Day of Week",
       y = "Count") +
  theme_minimal()

print(dow_plot)
```

```{r}
# accidents by month
month_plot <- ggplot(accident, aes(x = Start_Month)) +
  geom_bar(fill = "forestgreen") +
  labs(title = "Accidents by Month",
       x = "Month",
       y = "Count") +
  theme_minimal()

print(month_plot)
```























